### ISSUE TITLE
build fails with CPython2.7

### ISSUE THREAD

**Issue by marc1uk** [wlav/cppyy#36]
Hi again.
Trying to build with python 2.7 this time for older setups. The readthedocs page says 
> cppyy is available for both [CPython](http://python.org/) (v2 and v3) and [PyPy](http://pypy.org/)

so it seems it should be supported, but following the same steps as for python3 building from sources, I get
```
$ git clone https://github.com/wlav/cppyy-backend.git
Cloning into 'cppyy-backend'...
$ cd cppyy-backend
$ git checkout cppyy-cling-6.25.2
$ cd cling
$ python setup.py egg_info
Traceback (most recent call last):
  File "setup.py", line 395, in <module>
    packages=find_packages('python', include=['cppyy_backend']),
TypeError: find_packages() got an unexpected keyword argument 'include'
```

**Comment by wlav** [comment]
This isn't to do with python2.7 per se, as `find_packages()` is from `setuptools`, which I guess is old in the configuration used. What does `python2 -m pip show setuptools` list as version? On my Mac, with python2.7, I get 44.1.1, which isn't the latest by far (is at 60.8.2), but does already have that keyword. (In fact, a quick look at "blame" in setuptools' repo shows that the `include` keyword argument is at least 8 years old.)

**Comment by marc1uk** [comment]
```
user@host:~$ python2 -m pip show setuptools
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Name: setuptools
Version: 0.9.8
Summary: Easily download, build, install, upgrade, and uninstall Python packages
Home-page: https://pypi.python.org/pypi/setuptools
Author: Python Packaging Authority
Author-email: distutils-sig@python.org
License: PSF or ZPL
Location: /usr/lib/python2.7/site-packages
Requires: 
Required-by: 
```

hmm, is that.... version 0.9.8??? :joy: Apparently Centos7 is a little behind the times. I'll try to find some way to upgrade it....

**Comment by wlav** [comment]
That whole traceback is from pip and the failing command do not seem to have reached anything related to cppyy-cling yet (I also don't see `setuptools` in the trace, so no idea if/how having updated `setuptools` that could be connected).

That said, in modern pip, `SourceDistribution` apparently lives in `from pip._internal.distributions`, not in `pip._internal.distributions.source`.

Would it not make sense to run:
```
$ python -m pip install pip setuptools wheel --upgrade
```
prior to any other installation command? With py2.7, it should also be pretty safe as these tools are likely frozen for py2 at this point.

(Note that using a virtualenv should pick up the latest of the above automatically.)

**Comment by marc1uk** [comment]
i thought i'd done that, but perhaps not? It's getting difficult to track what works or doesn't without spinning up new containers and starting from fresh over and over. It seems like installing an updated pip results in the above error, which then occurs when trying to install any kind of python module at all - i just have to remove and reinstall python27-python-pip with yum. Haven't pinned down a version yet. 

For the time being the current latest point is installing CPyCppyy chokes with:
```
$ python -m pip install . --upgrade --no-deps
...
...
    src/Converters.cxx:32:19: fatal error: codecvt: No such file or directory
     #include <codecvt>
                       ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/opt/rh/python27/root/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-pbwWNq-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-9epfM1-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-pbwWNq-build/
```

It seems like <codecvt> wasn't added until relatively late in the gcc libstd; most recommendations i can find are to upgrade g++/devtoolset.  This wasn't needed for python3, any idea why it would be a problem with python2?

**Comment by wlav** [comment]
I can't help pip ... that whole stack trace is in `site-packages/pip`, so beats me how the installation could have gone awry.

As for `codecvt`, this is only included for Python2.7, hence it could ever only be a problem there. It's used for the `std::wstring` converter. Is this problem showing up with gcc4.8.5? An alternative implementation could have a conditional include of `codecvt` and if not available, let Python do the `char*` -> `wchar_t*` conversion by first converting to `PyUnicode`. That would be at the cost of an extra copy + conversion, but use of `str` through `std::wstring` in py2.7 is not going to be common, so that's probably acceptable.

**Comment by wlav** [comment]
Possible fix/workaround is in repo (https://github.com/wlav/CPyCppyy/commit/0060bd8bf786cc822e3b9e80e0233059e5c7e77c).

**Comment by marc1uk** [comment]
Unfortunately I'm on g++4.8.5, and __has_include seems to be a [g++5 feature](https://gcc.gnu.org/gcc-5/changes.html) :pensive:

**Comment by marc1uk** [comment]
Since covecvt ("locale facets for Unicode conversion") was introduced in g++5, i tried swapping it with a simple check:
`#if defined(__GNUC__) && __GNUC__ > 4` and that does seem to have allowed installation, and it looks like it's working!
Along with that change, i also had to remove the `#include` call and constant definition, since it seemed like the same behaviour was actually being performed in either branch of the check:
```
#if PY_VERSION_HEX < 0x03000000
-#if defined(__GNUC__) && __has_include("codecvt")
-#include <codecvt>
-#define HAS_CODECVT 1
-#else
+#if defined(__GNUC__) && __GNUC__ > 4
 #include <codecvt>
 #define HAS_CODECVT 1
 #endif
```

Thanks again for the support!
